<?php

/**
 * Module file for Field display per theme module.
 *
 * @TODO
 *   1. Replace field_ui display form constructor so other modules don't
 *      alter themselves in for free
 *   2. Field UI javascript replacement
 *   3. Replace refresh & submit submit handlers
 *   4. Hide 'default' view mode in overrides - doesn't make sense?
 *   5. Replace 'Custom display settings' with table, lock rows which are
 *      customly configurable in the base view mode already?
 *   6. Database table, or similar, for storage
 *   7. Features integration
 *   8. Export-to-a-theme functionality
 *   9. field_group integration
 *   10.
 */

/**
 * Implements hook_menu().
 */
function field_display_per_theme_menu() {
  $items = array();

  // Ensure the following is not executed until field_bundles is working and
  // tables are updated. Needed to avoid errors on initial installation.
  if (defined('MAINTENANCE_MODE')) {
    return $items;
  }

  // Override field display tab for each theme.
  foreach (list_themes() as $theme) {
    $items['admin/appearance/settings/' . $theme->name . '/field-display'] = array(
      'title' => 'Override field display',
      'page callback' => 'system_admin_menu_block_page',
      'type' => MENU_NORMAL_ITEM,
      'access callback' => 'field_display_per_theme_access',
      'access arguments' => array($theme),
      'file path' => drupal_get_path('module', 'system'),
      'file' => 'system.admin.inc',
    );

    // The following is based on field_ui_menu().

    // Create tabs for all possible bundles.
    foreach (entity_get_info() as $entity_type => $entity_info) {
      if ($entity_info['fieldable']) {

        $items['admin/appearance/settings/' . $theme->name . '/field-display/' . $entity_type] = array(
          'title' => 'Override field display',
          'title callback' => 'field_display_per_theme_title_callback',
          'title arguments' => array($theme->name, $entity_info['label'], $theme->info['name']),
          'type' => MENU_NORMAL_ITEM,
          'access callback' => 'field_display_per_theme_access',
          'access arguments' => array($theme),
        );

        // I can't seem to get the menu system to work with the above as a
        // default local task, so we make it a redirect to the first-selected
        // bundle tab.
        if (!empty($entity_info['bundles'])) {
          $bundle_names = array_keys($entity_info['bundles']);
          $first_bundle = reset($bundle_names);
          $items['admin/appearance/settings/' . $theme->name . '/field-display/' . $entity_type] += array(
            'page callback' => 'drupal_goto',
            'page arguments' => array('admin/appearance/settings/' . $theme->name . '/field-display/' . $entity_type . '/' . $first_bundle),
          );
        }

        $weight = 0;
        foreach ($entity_info['bundles'] as $bundle_name => $bundle_info) {
          if (isset($bundle_info['admin'])) {

            $bundle_arg = 6;
            $access = array_intersect_key($bundle_info['admin'], drupal_map_assoc(array('access callback', 'access arguments')));
            $access += array(
              'access callback' => 'user_access',
              'access arguments' => array('administer site configuration'),
            );

            $items['admin/appearance/settings/' . $theme->name . '/field-display/' . $entity_type . '/' . $bundle_name] = array(
              'title' => $bundle_info['label'],
              'page callback' => 'field_display_per_theme_display_overview_page',
              'page arguments' => array($theme->name, $entity_type, $bundle_arg, 'default'),
              'type' => MENU_LOCAL_TASK,
              'file' => 'field_display_per_theme.admin.inc',
              'weight' => $weight++,
            ) + $access;

            $view_mode_weight = 0;
            $view_modes = array('default' => array('label' => t('Default'))) + $entity_info['view modes'];
            foreach ($view_modes as $view_mode => $view_mode_info) {

              $items['admin/appearance/settings/' . $theme->name . '/field-display/' . $entity_type . '/' . $bundle_name . '/' . $view_mode] = array(
                'title' => $view_mode_info['label'],
                'page arguments' => array($theme->name, $entity_type, $bundle_arg, $view_mode),
                // The access callback needs to check both the current 'custom
                // display' setting for the view mode, and the overall access
                // rules for the bundle admin pages.
                'access callback' => '_field_ui_view_mode_menu_access',
                'access arguments' => array_merge(array($entity_type, $bundle_arg, $view_mode, $access['access callback']), $access['access arguments']),
                'type' => ($view_mode == 'default' ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK),
                'weight' => ($view_mode == 'default' ? -10 : $view_mode_weight++),
                'file' => 'field_display_per_theme.admin.inc',
              );
            }
          }
        }
      }
    }
  }

  return $items;
}

/**
 * Implements hook_forms().
 */
function field_display_per_theme_forms($form_id, $args) {
  $forms = array();

  $forms['field_display_per_theme_display_overview_form'] = array(
    'callback' => 'field_ui_display_overview_form',
    'wrapper_callback' => 'field_display_per_theme_display_overview_form_wrapper',
  );

  return $forms;
}

/**
 * Menu title callback.
 *
 * @param $theme_key
 * @param $entity_type_label
 * @param $theme_label
 *
 * @return null|string
 */
function field_display_per_theme_title_callback($theme_key, $entity_type_label, $theme_label) {
  // Keep it simple on the listing page.
  if (current_path() === 'admin/appearance/settings/' . $theme_key . '/field-display') {
    return check_plain($entity_type_label);
  }
  else {
    return t('Override @entity_type_label field display in @theme_name', array('@entity_type_label' => $entity_type_label, '@theme_name' => $theme_label));
  }
}

/**
 * Determine if the current user has access to the field display overrides
 * page on a certain theme.
 *
 * @param $theme
 * @return bool
 */
function field_display_per_theme_access($theme) {
  return _system_themes_access($theme) && user_access('administer site configuration');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Detects our special version of the Manage Display form and alters it.
 */
function field_display_per_theme_form_field_ui_display_overview_form_alter(&$form, &$form_state) {
  if (isset($form_state['field_display_per_theme'])) {
    // No need to call form_load_include() here because our admin.inc file is
    // already included and logged in $form_state by the Drupal menu system.
    _field_display_per_theme_form_field_ui_display_overview_form_alter($form, $form_state);
  }
}

/**
 * Loads our override field display config.
 */
function field_display_per_theme_config_load() {
  return array(
    'field_image' => array(
      'label' => 'above',
      'settings' => array(
        'image_style' => 'medium',
        'image_link' => '',
      ),
    ),
  );
}